export const ARC_LINKS = [
  ['Seoul', 'Tokyo'],
  ['Seoul', 'Singapore'],
  ['Tokyo', 'San Francisco'],
  ['New York', 'London'],
  ['London', 'Sao Paulo'],
  ['San Francisco', 'Sydney'],
];

export const ARC_LINKS_EXTENDED = [
  ...ARC_LINKS,
  ['Seoul', 'New York'],
  ['Tokyo', 'London'],
  ['Singapore', 'San Francisco'],
  ['New York', 'Sao Paulo'],
];

export const GLOBE_THEMES = {
  a: {
    id: 'a',
    label: 'A',
    name: 'Obsidian Premium',
    tagline: '펄스 비콘 · 골드',
    showGrain: true,
    showOrbitRing: true,
    showSecondaryGlow: true,
    showAurora: false,
    globe: {
      globeImageUrl: 'https://unpkg.com/three-globe/example/img/earth-night.jpg',
      bumpImageUrl: 'https://unpkg.com/three-globe/example/img/earth-topology.png',
      atmosphereColor: '#c9a84c',
      atmosphereAltitude: 0.2,
      pointStyle: {
        type: 'beacon',
        color: '#e8c872',
        glowColor: '#ffd875',
        baseSize: 24,
        sizeScale: 9,
      },
      ringRgb: '232, 200, 114',
      ringOpacity: 0.6,
      ringMaxRadiusScale: 2.8,
      ringPropagationSpeed: 1.8,
      ringRepeatPeriod: 1300,
      ringLayers: 3,
      ringLayerDelay: 550,
      showArcs: true,
      arcLinks: ARC_LINKS,
      arcColor: 'rgba(201, 168, 76, 0.32)',
      arcAltitude: 0.2,
      arcStroke: 0.4,
      arcDashLength: 0.45,
      arcDashGap: 0.2,
      arcDashAnimateTime: 2600,
      autoRotateSpeed: 0.3,
      pointOfView: { lat: 18, lng: 115, altitude: 2.3 },
    },
  },
  b: {
    id: 'b',
    label: 'B',
    name: 'Aurora Network',
    tagline: '레이더 스윕 · 시안',
    showGrain: true,
    showOrbitRing: true,
    showSecondaryGlow: true,
    showAurora: true,
    globe: {
      globeImageUrl: 'https://unpkg.com/three-globe/example/img/earth-night.jpg',
      bumpImageUrl: 'https://unpkg.com/three-globe/example/img/earth-topology.png',
      atmosphereColor: '#38bdf8',
      atmosphereAltitude: 0.24,
      pointStyle: {
        type: 'radar',
        color: '#5eead4',
        glowColor: '#38bdf8',
        baseSize: 28,
        sizeScale: 10,
      },
      ringRgb: '94, 234, 212',
      ringOpacity: 0.75,
      ringMaxRadiusScale: 3.2,
      ringPropagationSpeed: 2.4,
      ringRepeatPeriod: 1000,
      ringLayers: 3,
      ringLayerDelay: 400,
      showArcs: true,
      arcLinks: ARC_LINKS,
      arcColor: 'rgba(56, 189, 248, 0.48)',
      arcAltitude: 0.24,
      arcStroke: 0.5,
      arcDashLength: 0.55,
      arcDashGap: 0.12,
      arcDashAnimateTime: 2000,
      autoRotateSpeed: 0.38,
      pointOfView: { lat: 22, lng: 100, altitude: 2.15 },
    },
  },
  c: {
    id: 'c',
    label: 'C',
    name: 'Monochrome Atlas',
    tagline: '스파클 · 실버',
    showGrain: false,
    showOrbitRing: true,
    showSecondaryGlow: false,
    showAurora: false,
    globe: {
      globeImageUrl: 'https://unpkg.com/three-globe/example/img/earth-night.jpg',
      bumpImageUrl: 'https://unpkg.com/three-globe/example/img/earth-topology.png',
      atmosphereColor: '#94a3b8',
      atmosphereAltitude: 0.14,
      pointStyle: {
        type: 'spark',
        color: '#e2e8f0',
        glowColor: '#ffffff',
        baseSize: 20,
        sizeScale: 7,
      },
      ringRgb: '226, 232, 240',
      ringOpacity: 0.45,
      ringMaxRadiusScale: 2.2,
      ringPropagationSpeed: 1.3,
      ringRepeatPeriod: 1900,
      ringLayers: 2,
      ringLayerDelay: 900,
      showArcs: false,
      autoRotateSpeed: 0.24,
      pointOfView: { lat: 20, lng: 10, altitude: 2.35 },
    },
  },
  d: {
    id: 'd',
    label: 'D',
    name: 'Inferno Command',
    tagline: '서지 버스트 · 레드',
    showGrain: true,
    showOrbitRing: true,
    showOrbitRingOuter: true,
    showSecondaryGlow: true,
    showAurora: false,
    showEnergyBurst: true,
    globe: {
      globeImageUrl: 'https://unpkg.com/three-globe/example/img/earth-night.jpg',
      bumpImageUrl: 'https://unpkg.com/three-globe/example/img/earth-topology.png',
      atmosphereColor: '#f97316',
      atmosphereAltitude: 0.26,
      pointStyle: {
        type: 'surge',
        color: '#fb923c',
        glowColor: '#ef4444',
        baseSize: 30,
        sizeScale: 11,
      },
      ringRgb: '251, 146, 60',
      ringOpacity: 0.8,
      ringMaxRadiusScale: 3.5,
      ringPropagationSpeed: 2.8,
      ringRepeatPeriod: 850,
      ringLayers: 4,
      ringLayerDelay: 320,
      showArcs: true,
      arcLinks: ARC_LINKS_EXTENDED,
      arcColor: 'rgba(239, 68, 68, 0.55)',
      arcAltitude: 0.28,
      arcStroke: 0.55,
      arcDashLength: 0.35,
      arcDashGap: 0.08,
      arcDashAnimateTime: 1600,
      autoRotateSpeed: 0.42,
      pointOfView: { lat: 15, lng: 130, altitude: 2.1 },
    },
  },
  e: {
    id: 'e',
    label: 'E',
    name: 'Quantum Edge',
    tagline: '플럭스 코어 · 퍼플',
    showGrain: true,
    showOrbitRing: true,
    showSecondaryGlow: true,
    showAurora: false,
    showScanlines: true,
    globe: {
      globeImageUrl: 'https://unpkg.com/three-globe/example/img/earth-night.jpg',
      bumpImageUrl: 'https://unpkg.com/three-globe/example/img/earth-topology.png',
      atmosphereColor: '#a855f7',
      atmosphereAltitude: 0.28,
      pointStyle: {
        type: 'flux',
        color: '#c084fc',
        glowColor: '#818cf8',
        baseSize: 32,
        sizeScale: 10,
      },
      ringRgb: '192, 132, 252',
      ringOpacity: 0.85,
      ringMaxRadiusScale: 3.8,
      ringPropagationSpeed: 3,
      ringRepeatPeriod: 750,
      ringLayers: 4,
      ringLayerDelay: 280,
      showArcs: true,
      arcLinks: ARC_LINKS_EXTENDED,
      arcColor: 'rgba(168, 85, 247, 0.58)',
      arcAltitude: 0.3,
      arcStroke: 0.6,
      arcDashLength: 0.25,
      arcDashGap: 0.05,
      arcDashAnimateTime: 1200,
      autoRotateSpeed: 0.45,
      pointOfView: { lat: 25, lng: 80, altitude: 2.05 },
    },
  },
  f: {
    id: 'f',
    label: 'F',
    name: 'Nexus Live',
    tagline: '시그널 업 · 그린',
    showGrain: true,
    showOrbitRing: true,
    showSecondaryGlow: true,
    showAurora: false,
    showGrid: true,
    globe: {
      globeImageUrl: 'https://unpkg.com/three-globe/example/img/earth-night.jpg',
      bumpImageUrl: 'https://unpkg.com/three-globe/example/img/earth-topology.png',
      atmosphereColor: '#34d399',
      atmosphereAltitude: 0.22,
      pointStyle: {
        type: 'signal',
        color: '#4ade80',
        glowColor: '#22d3ee',
        baseSize: 28,
        sizeScale: 9,
      },
      ringRgb: '74, 222, 128',
      ringOpacity: 0.7,
      ringMaxRadiusScale: 3.2,
      ringPropagationSpeed: 2.5,
      ringRepeatPeriod: 950,
      ringLayers: 3,
      ringLayerDelay: 380,
      showArcs: true,
      arcLinks: ARC_LINKS_EXTENDED,
      arcColor: 'rgba(52, 211, 153, 0.5)',
      arcAltitude: 0.25,
      arcStroke: 0.5,
      arcDashLength: 0.5,
      arcDashGap: 0.1,
      arcDashAnimateTime: 1800,
      autoRotateSpeed: 0.36,
      pointOfView: { lat: 12, lng: 150, altitude: 2.15 },
    },
  },
  g: {
    id: 'g',
    label: 'G',
    name: 'Luminous Day',
    tagline: '라이트 · 골드',
    isLight: true,
    showGrain: false,
    showOrbitRing: true,
    showSecondaryGlow: true,
    showAurora: false,
    showSoftLight: true,
    globe: {
      globeImageUrl: 'https://unpkg.com/three-globe/example/img/earth-blue-marble.jpg',
      bumpImageUrl: 'https://unpkg.com/three-globe/example/img/earth-topology.png',
      atmosphereColor: '#d97706',
      atmosphereAltitude: 0.16,
      pointStyle: {
        type: 'beacon',
        color: '#78350f',
        glowColor: '#b45309',
        baseSize: 28,
        sizeScale: 11,
      },
      ringRgb: '146, 64, 14',
      ringOpacity: 0.72,
      ringMaxRadiusScale: 2.6,
      ringPropagationSpeed: 1.7,
      ringRepeatPeriod: 1350,
      ringLayers: 3,
      ringLayerDelay: 520,
      showArcs: true,
      arcLinks: ARC_LINKS,
      arcColor: 'rgba(120, 53, 15, 0.55)',
      arcAltitude: 0.18,
      arcStroke: 0.42,
      arcDashLength: 0.45,
      arcDashGap: 0.18,
      arcDashAnimateTime: 2400,
      autoRotateSpeed: 0.3,
      pointOfView: { lat: 18, lng: 115, altitude: 2.3 },
    },
  },
  h: {
    id: 'h',
    label: 'H',
    name: 'Sky Analytics',
    tagline: '라이트 · 블루',
    isLight: true,
    showGrain: false,
    showOrbitRing: true,
    showSecondaryGlow: true,
    showAurora: false,
    showCloudWash: true,
    globe: {
      globeImageUrl: 'https://unpkg.com/three-globe/example/img/earth-blue-marble.jpg',
      bumpImageUrl: 'https://unpkg.com/three-globe/example/img/earth-topology.png',
      atmosphereColor: '#0284c7',
      atmosphereAltitude: 0.18,
      pointStyle: {
        type: 'radar',
        color: '#0c4a6e',
        glowColor: '#0369a1',
        baseSize: 30,
        sizeScale: 11,
      },
      ringRgb: '3, 105, 161',
      ringOpacity: 0.68,
      ringMaxRadiusScale: 2.8,
      ringPropagationSpeed: 2,
      ringRepeatPeriod: 1150,
      ringLayers: 3,
      ringLayerDelay: 420,
      showArcs: true,
      arcLinks: ARC_LINKS,
      arcColor: 'rgba(3, 105, 161, 0.58)',
      arcAltitude: 0.2,
      arcStroke: 0.46,
      arcDashLength: 0.5,
      arcDashGap: 0.14,
      arcDashAnimateTime: 2100,
      autoRotateSpeed: 0.34,
      pointOfView: { lat: 22, lng: 100, altitude: 2.2 },
    },
  },
  i: {
    id: 'i',
    label: 'I',
    name: 'Pearl Enterprise',
    tagline: '라이트 · 실버',
    isLight: true,
    showGrain: false,
    showOrbitRing: true,
    showSecondaryGlow: false,
    showAurora: false,
    showPaperTexture: true,
    globe: {
      globeImageUrl: 'https://unpkg.com/three-globe/example/img/earth-blue-marble.jpg',
      bumpImageUrl: 'https://unpkg.com/three-globe/example/img/earth-topology.png',
      atmosphereColor: '#64748b',
      atmosphereAltitude: 0.12,
      pointStyle: {
        type: 'spark',
        color: '#0f172a',
        glowColor: '#334155',
        baseSize: 28,
        sizeScale: 10,
      },
      ringRgb: '15, 23, 42',
      ringOpacity: 0.58,
      ringMaxRadiusScale: 2.2,
      ringPropagationSpeed: 1.4,
      ringRepeatPeriod: 1800,
      ringLayers: 2,
      ringLayerDelay: 850,
      showArcs: true,
      arcLinks: ARC_LINKS,
      arcColor: 'rgba(15, 23, 42, 0.48)',
      arcAltitude: 0.16,
      arcStroke: 0.38,
      arcDashLength: 0.55,
      arcDashGap: 0.2,
      arcDashAnimateTime: 2600,
      autoRotateSpeed: 0.26,
      pointOfView: { lat: 20, lng: 10, altitude: 2.35 },
    },
  },
};

export const THEME_IDS = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'];
